use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/* -------------------------------------------------------------------------
 * .cart.info section data
 *
 * 8-byte preamble (ADR-0073): "CINF" + format_major(u16le=0) + format_minor(u16le=0)
 * followed by the FlatBuffers CartInfo table with api_version_major=0 and
 * api_version_minor=0 (12 bytes as produced by flatcc for this schema).
 * ------------------------------------------------------------------------- */
const CART_INFO: &[u8] = &[
    b'C', b'I', b'N', b'F', 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0xfc, 0xff, 0xff, 0xff,
    0x04, 0x00, 0x04, 0x00,
];

/* -------------------------------------------------------------------------
 * Linker script (ADR-0024, ADR-0112)
 *
 * Produces an ET_DYN (PIE) RV32 ELF with PT_INTERP = /lib/ld-blyt.so.1 and
 * DT_NEEDED: libblyt32.so.
 *
 * PT_INTERP makes the cart a valid native executable on any system that has
 * /lib/ld-blyt.so.1 (a symlink to the platform's ILP32 dynamic linker).
 * On the emulated path, blyt's custom dynlinker ignores PT_INTERP and
 * handles DT_NEEDED resolution directly.
 *
 * PIE (ET_DYN) is required on the native path: the c-sky ILP32 kernel patch
 * computes AT_PHDR incorrectly for ET_EXEC carts (-no-pie), causing a segfault
 * in musl's startup. ET_DYN carts work correctly.
 *
 * ELF congruence (p_vaddr % p_align == p_offset % p_align):
 *   FILEHDR PHDRS in the text PT_LOAD anchors p_offset=0.  With p_vaddr=0
 *   (PIE, sections start at 0), both sides are 0 mod 0x1000. The ld.so maps
 *   the binary at a runtime base B chosen by the OS (≥ mmap_min_addr), so
 *   all virtual addresses are B + script_vaddr — no fixed-address constraint.
 *
 * Security requirements (ADR-0112):
 *   - PT_INTERP = /lib/ld-blyt.so.1 (required; validated at cart load time)
 *   - PT_GNU_RELRO + BIND_NOW: explicit relro PHDR + -z,relro -z,now
 *   - No ecall in cart code: cart calls blyt API via PLT only
 *   - Entry point in PF_X PT_LOAD segment: _blyt_entry in cart .text
 * ------------------------------------------------------------------------- */
const LINKER_SCRIPT: &str = "ENTRY(_blyt_entry)
";

/* -------------------------------------------------------------------------
 * Error type
 * ------------------------------------------------------------------------- */

#[derive(Debug)]
pub struct BuildError(String);

impl std::fmt::Display for BuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<std::io::Error> for BuildError {
    fn from(e: std::io::Error) -> Self {
        BuildError(e.to_string())
    }
}

fn err(msg: impl Into<String>) -> BuildError {
    BuildError(msg.into())
}

/* -------------------------------------------------------------------------
 * Public entry point
 * ------------------------------------------------------------------------- */

pub fn run(project_dir: &Path, output: Option<&Path>) -> Result<PathBuf, BuildError> {
    let clang = find_clang();
    let objcopy = find_objcopy();

    let sdk_include = find_sdk_include()?;
    let lib_dir = find_lib_dir(&sdk_include)?;

    let c_src_dir = project_dir.join("src/game/c");
    let c_files = collect_c_files(&c_src_dir)?;
    if c_files.is_empty() {
        return Err(err(format!(
            "no .c files found under {}",
            c_src_dir.display()
        )));
    }

    let build_dir = project_dir.join("build/game/c");
    fs::create_dir_all(&build_dir)?;

    let ld_script = build_dir.join("blyt_cart.ld");
    fs::write(&ld_script, LINKER_SCRIPT)?;

    let cart_info_file = build_dir.join("cart.info.bin");
    fs::write(&cart_info_file, CART_INFO)?;

    /* Generate the cart entry point stub.  _blyt_entry is the ELF e_entry:
     *   - On native RISC-V hardware: ld.so jumps here after loading
     *     libblyt32.so and libblytcommon.so; it calls blyt_main via PLT.
     *   - In the emulator: rv_create sets PC = e_entry = _blyt_entry;
     *     the PLT entry for blyt_main is resolved by dynlink before rv_run.
     * The load-time security check requires e_entry to be within an
     * executable PT_LOAD segment of the cart, which _blyt_entry satisfies. */
    let entry_stub_src = build_dir.join("_blyt_entry.c");
    fs::write(
        &entry_stub_src,
        "/* Generated by blyt build — do not edit. */\n\
         void blyt_main(void);\n\
         /* blyt_exit is provided by the native libblyt32.so (calls exit_group).\n\
          * On the emulated path the dynamic linker never calls ELF constructors,\n\
          * so blyt_exit is never reached; the emulator halts on ECALL_QUIT. */\n\
         __attribute__((noreturn)) void blyt_exit(int code);\n\
         void _blyt_entry(void) {\n\
             blyt_main();\n\
             blyt_exit(0);\n\
         }\n",
    )?;

    /* Generate the PT_INTERP section.  lld does not populate the .interp
     * phdr from a custom PHDRS linker script via --dynamic-linker; an
     * explicit input section is required. */
    let interp_src = build_dir.join("_blyt_interp.c");
    fs::write(
        &interp_src,
        "/* Generated by blyt build — do not edit. */\n\
         __attribute__((section(\".interp\"), used))\n\
         static const char blyt_interp[] = \"/lib/ld-blyt.so.1\";\n",
    )?;

    let mut obj_files = Vec::new();
    obj_files.push(compile_c(
        &clang,
        &entry_stub_src,
        &build_dir,
        &sdk_include,
    )?);
    obj_files.push(compile_c(&clang, &interp_src, &build_dir, &sdk_include)?);
    for src in &c_files {
        let obj = compile_c(&clang, src, &build_dir, &sdk_include)?;
        obj_files.push(obj);
    }

    let raw_elf = build_dir.join("cart.elf");
    link_cart(&clang, &obj_files, &ld_script, &lib_dir, &raw_elf)?;

    let output_path = output
        .map(PathBuf::from)
        .unwrap_or_else(|| default_output(project_dir));

    finalise_cart(&objcopy, &raw_elf, &cart_info_file, &output_path)?;

    println!("built: {}", output_path.display());
    Ok(output_path)
}

fn default_output(project_dir: &Path) -> PathBuf {
    let name = project_dir
        .file_name()
        .and_then(OsStr::to_str)
        .unwrap_or("cart");
    project_dir.with_file_name(format!("{name}.blyt"))
}

/* -------------------------------------------------------------------------
 * Toolchain discovery
 *
 * Resolution order for clang and llvm-objcopy:
 *   1. $BLYT_CLANG / $BLYT_OBJCOPY environment variables
 *   2. <sdk>/toolchain/bin/  — when running from a built SDK (build/sdk/bin/)
 *   3. System PATH fallback
 * ------------------------------------------------------------------------- */

pub(crate) fn sdk_root_from_exe() -> Option<PathBuf> {
    // Binary is at <sdk>/bin/blyt; SDK root is the parent of bin/.
    std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().and_then(|b| b.parent().map(PathBuf::from)))
}

fn find_clang() -> String {
    if let Ok(c) = std::env::var("BLYT_CLANG") {
        return c;
    }
    // SDK layout: use the blyt-prefixed clang symlink from bin/
    if let Some(sdk) = sdk_root_from_exe() {
        let p = sdk.join("bin/blyt-clang");
        if p.exists() {
            return p.to_string_lossy().into_owned();
        }
    }
    "clang".to_string()
}

fn find_objcopy() -> String {
    if let Ok(o) = std::env::var("BLYT_OBJCOPY") {
        return o;
    }
    // SDK layout: use the blyt-prefixed objcopy symlink from bin/
    if let Some(sdk) = sdk_root_from_exe() {
        let p = sdk.join("bin/blyt-objcopy");
        if p.exists() {
            return p.to_string_lossy().into_owned();
        }
    }
    "llvm-objcopy".to_string()
}

/* -------------------------------------------------------------------------
 * SDK include directory
 *
 * Looks for the directory containing blyt.h:
 *   1. $BLYT_SDK_DIR/include (or $BLYT_SDK_DIR if blyt.h is directly inside)
 *   2. <sdk>/include/ — when running from a built SDK (build/sdk/bin/)
 *   3. Ancestors of the running binary
 * ------------------------------------------------------------------------- */

fn find_sdk_include() -> Result<PathBuf, BuildError> {
    if let Ok(sdk) = std::env::var("BLYT_SDK_DIR") {
        let sdk = PathBuf::from(sdk);
        let via_include = sdk.join("include");
        if via_include.join("blyt.h").exists() {
            return Ok(via_include);
        }
        return Err(err(format!(
            "BLYT_SDK_DIR={} does not contain include/blyt.h",
            sdk.display()
        )));
    }

    // SDK layout: <sdk>/include/blyt.h when running from <sdk>/bin/blyt
    if let Some(sdk) = sdk_root_from_exe() {
        let p = sdk.join("include/blyt.h");
        if p.exists() {
            return Ok(sdk.join("include"));
        }
    }

    // Repo layout: walk up from the binary looking for runtime/guest/include/blyt.h
    if let Ok(exe) = std::env::current_exe() {
        for ancestor in exe.ancestors().skip(1) {
            let candidate = ancestor.join("runtime/guest/include").join("blyt.h");
            if candidate.exists() {
                return Ok(ancestor.join("runtime/guest/include"));
            }
        }
    }

    Err(err(
        "cannot find blyt.h — run `cmake --build build --target sdk` \
         and use build/sdk/bin/blyt, or set BLYT_SDK_DIR",
    ))
}

/* -------------------------------------------------------------------------
 * Library directory
 *
 * Looks for the directory containing libblyt32.so:
 *   1. $BLYT_LIB_DIR  (explicit override)
 *   2. $BLYT_SDK_DIR/lib/  — derived from SDK dir
 *   3. <sdk>/lib/  — SDK layout (running from build/sdk/bin/blyt)
 *   4. Walk up from sdk_include looking for build/sdk/lib/ or build/
 * ------------------------------------------------------------------------- */

fn find_lib_dir(sdk_include: &Path) -> Result<PathBuf, BuildError> {
    if let Ok(d) = std::env::var("BLYT_LIB_DIR") {
        let p = PathBuf::from(d);
        if p.join("libblyt32.so").exists() {
            return Ok(p);
        }
    }

    // Derive from BLYT_SDK_DIR: lib/ is always adjacent to include/
    if let Ok(sdk) = std::env::var("BLYT_SDK_DIR") {
        let p = PathBuf::from(sdk).join("lib");
        if p.join("libblyt32.so").exists() {
            return Ok(p);
        }
    }

    // SDK layout: <sdk>/lib/libblyt32.so when running from <sdk>/bin/blyt
    if let Some(sdk) = sdk_root_from_exe() {
        let p = sdk.join("lib");
        if p.join("libblyt32.so").exists() {
            return Ok(p);
        }
    }

    // Repo layout: walk up from sdk_include looking for build/sdk/lib/ or build/
    // sdk_include may be deep inside the repo (e.g. runtime/guest/include),
    // so we walk ancestors rather than assuming a fixed depth.
    let mut dir = sdk_include.to_path_buf();
    while let Some(parent) = dir.parent() {
        dir = parent.to_path_buf();
        for subdir in &["build/sdk/lib", "build"] {
            let candidate = dir.join(subdir);
            if candidate.join("libblyt32.so").exists() {
                return Ok(candidate);
            }
        }
    }

    Err(err(
        "cannot find libblyt32.so — run `cmake --build build --target sdk` \
         to build the blyt SDK, then use build/sdk/bin/blyt",
    ))
}

/* -------------------------------------------------------------------------
 * Source file discovery — all .c files under dir, recursively
 * ------------------------------------------------------------------------- */

fn collect_c_files(dir: &Path) -> Result<Vec<PathBuf>, BuildError> {
    if !dir.exists() {
        return Ok(Vec::new());
    }
    let mut files = Vec::new();
    collect_c_recursive(dir, &mut files)?;
    files.sort();
    Ok(files)
}

fn collect_c_recursive(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), BuildError> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_c_recursive(&path, out)?;
        } else if path.extension().and_then(OsStr::to_str) == Some("c") {
            out.push(path);
        }
    }
    Ok(())
}

/* -------------------------------------------------------------------------
 * Compilation: one .c → one .o
 * ------------------------------------------------------------------------- */

fn compile_c(
    clang: &str,
    src: &Path,
    build_dir: &Path,
    sdk_include: &Path,
) -> Result<PathBuf, BuildError> {
    let stem = src.file_stem().and_then(OsStr::to_str).unwrap_or("unknown");
    let obj = build_dir.join(format!("{stem}.o"));

    let status = Command::new(clang)
        .args([
            "--target=riscv32",
            "-march=rv32imafc",
            "-mabi=ilp32f",
            "-nostdlib",
            "-fno-exceptions",
            "-fpie",
            // Determinism flags (ADR-0007): IEEE 754 strict mode.
            // -ffp-contract=off  — no implicit FMA fusion (changes rounding)
            // -fno-fast-math     — no IEEE-breaking optimisations
            // -fwrapv            — signed integer overflow wraps (no UB)
            // -frounding-math    — compiler must not assume RNE is fixed
            // -fsignaling-nans   — NaN operations may signal; no elision
            "-ffp-contract=off",
            "-fno-fast-math",
            "-fwrapv",
            "-frounding-math",
            "-fsignaling-nans",
            "-c",
        ])
        .arg("-I")
        .arg(sdk_include)
        .arg("-o")
        .arg(&obj)
        .arg(src)
        .status()
        .map_err(|e| err(format!("failed to run {clang}: {e}")))?;

    if !status.success() {
        return Err(err(format!("compilation failed: {}", src.display())));
    }
    Ok(obj)
}

/* -------------------------------------------------------------------------
 * Linking: .o files → raw ELF (ET_DYN/PIE, dynamically linked against libblyt32.so)
 *
 * _blyt_interp.c       provides the .interp input section (PT_INTERP =
 *                      /lib/ld-blyt.so.1); lld needs an explicit input section
 *                      to populate PT_INTERP from a custom PHDRS script
 * -pie                 ET_DYN; required on the native path — the c-sky ILP32
 *                      kernel computes AT_PHDR incorrectly for ET_EXEC carts
 * -z,relro -z,now      BIND_NOW + RELRO required by ADR-0112
 * -Bdynamic            override clang's -Bstatic injection for bare-metal riscv
 * -lblyt32             creates DT_NEEDED: libblyt32.so and PLT/GOT entries
 * -lblytcommon         resolves symbols from libblytcommon.so; lld does not
 *                      follow DT_NEEDED chains transitively during link
 * ------------------------------------------------------------------------- */

fn link_cart(
    clang: &str,
    objs: &[PathBuf],
    ld_script: &Path,
    lib_dir: &Path,
    output: &Path,
) -> Result<(), BuildError> {
    let mut cmd = Command::new(clang);

    // Use the SDK's own lld via absolute path when available.  -fuse-ld=<abs>
    // is accepted by clang unconditionally and is unambiguous regardless of
    // PATH or clang's own-directory lookup order.  The blyt-ld.lld symlink
    // name avoids clashing with any system ld.lld when sdk/bin/ is on PATH
    // or installed into a shared directory.
    //
    // Fallback to -fuse-ld=lld when blyt-ld.lld is not present: outside the
    // SDK (e.g. target/debug/ during development), or on Windows where the
    // binary would be blyt-ld.lld.exe and the install-conflict concern does
    // not apply anyway (no shared /usr/bin convention).
    let fuse_ld = sdk_root_from_exe()
        .map(|sdk| sdk.join("bin").join("blyt-ld.lld"))
        .filter(|p| p.exists())
        .map(|p| format!("-fuse-ld={}", p.display()))
        .unwrap_or_else(|| "-fuse-ld=lld".to_string());
    cmd.args([
        "--target=riscv32",
        "-march=rv32imafc",
        "-mabi=ilp32f",
        "-nostdlib",
    ])
    .arg(&fuse_ld)
    .args([
        "-Wl,--pic-executable",
        "-Wl,-Bdynamic",
        // PT_INTERP is set via the explicit _blyt_interp.c .interp section.
        // lld does not populate PT_INTERP from --dynamic-linker when a custom
        // PHDRS linker script is in use; an input .interp section is required.
        "-Wl,-z,relro",
        "-Wl,-z,now",
        "-Wl,--build-id=none",
    ])
    .arg(format!("-T{}", ld_script.display()))
    .arg("-o")
    .arg(output);

    for obj in objs {
        cmd.arg(obj);
    }

    // Link against libblyt32.so only; the cart's DT_NEEDED is {libblyt32.so}.
    // The SDK's libblyt32.so absorbs all libblytc sources (malloc, string,
    // math, etc.) so lld resolves them directly from libblyt32.so's .dynsym.
    // libblytc.so is loaded at runtime via libblyt32.so's DT_NEEDED entry.
    cmd.arg("-L").arg(lib_dir).arg("-lblyt32");

    let status = cmd
        .status()
        .map_err(|e| err(format!("failed to run {clang}: {e}")))?;

    if !status.success() {
        return Err(err("link failed"));
    }
    Ok(())
}

/* -------------------------------------------------------------------------
 * Cart finalisation: inject .cart.info, strip toolchain metadata
 *
 * .riscv.attributes and .comment are toolchain metadata with no runtime use.
 * ------------------------------------------------------------------------- */

fn finalise_cart(
    objcopy: &str,
    raw_elf: &Path,
    cart_info_file: &Path,
    output: &Path,
) -> Result<(), BuildError> {
    let status = Command::new(objcopy)
        .arg("--add-section")
        .arg(format!(".cart.info={}", cart_info_file.display()))
        .arg("--set-section-flags")
        .arg(".cart.info=alloc,readonly")
        .arg("--remove-section=.riscv.attributes")
        .arg("--remove-section=.comment")
        .arg(raw_elf)
        .arg(output)
        .status()
        .map_err(|e| err(format!("failed to run {objcopy}: {e}")))?;

    if !status.success() {
        return Err(err("objcopy (finalise) failed"));
    }
    Ok(())
}
