// Generated FlatBuffers bindings for the .cart.info section (ADR-0073, ADR-0129).
//
// Regenerate after editing schemas/cart_info.fbs with:
//
//     flatc --rust -o devtool/src schemas/cart_info.fbs && cargo fmt -p blyt
//
// (the `cargo fmt` pass is required: CI runs `cargo fmt --check --all`, which
// covers this file, and raw flatc output is not rustfmt-clean.)
// flatc 25.12.19; must stay version-matched with the `flatbuffers` crate in
// devtool/Cargo.toml. The C reader is generated separately by flatcc via the
// CMake custom command — the wire format is identical regardless of codegen.
//
// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod blyt {

    pub enum CartInfoOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct CartInfo<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for CartInfo<'a> {
        type Inner = CartInfo<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> CartInfo<'a> {
        pub const VT_API_VERSION_MAJOR: ::flatbuffers::VOffsetT = 4;
        pub const VT_API_VERSION_MINOR: ::flatbuffers::VOffsetT = 6;
        pub const VT_TITLE: ::flatbuffers::VOffsetT = 8;
        pub const VT_AUTHOR: ::flatbuffers::VOffsetT = 10;
        pub const VT_CONSOLE: ::flatbuffers::VOffsetT = 12;
        pub const VT_DEBUG: ::flatbuffers::VOffsetT = 14;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            CartInfo { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args CartInfoArgs<'args>,
        ) -> ::flatbuffers::WIPOffset<CartInfo<'bldr>> {
            let mut builder = CartInfoBuilder::new(_fbb);
            if let Some(x) = args.console {
                builder.add_console(x);
            }
            if let Some(x) = args.author {
                builder.add_author(x);
            }
            if let Some(x) = args.title {
                builder.add_title(x);
            }
            builder.add_api_version_minor(args.api_version_minor);
            builder.add_api_version_major(args.api_version_major);
            builder.add_debug(args.debug);
            builder.finish()
        }

        #[inline]
        pub fn api_version_major(&self) -> u16 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u16>(CartInfo::VT_API_VERSION_MAJOR, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn api_version_minor(&self) -> u16 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u16>(CartInfo::VT_API_VERSION_MINOR, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn title(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(CartInfo::VT_TITLE, None)
            }
        }
        #[inline]
        pub fn author(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(CartInfo::VT_AUTHOR, None)
            }
        }
        #[inline]
        pub fn console(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<::flatbuffers::ForwardsUOffset<&str>>(CartInfo::VT_CONSOLE, None)
            }
        }
        #[inline]
        pub fn debug(&self) -> bool {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<bool>(CartInfo::VT_DEBUG, Some(false))
                    .unwrap()
            }
        }
    }

    impl ::flatbuffers::Verifiable for CartInfo<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<u16>("api_version_major", Self::VT_API_VERSION_MAJOR, false)?
                .visit_field::<u16>("api_version_minor", Self::VT_API_VERSION_MINOR, false)?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "title",
                    Self::VT_TITLE,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "author",
                    Self::VT_AUTHOR,
                    false,
                )?
                .visit_field::<::flatbuffers::ForwardsUOffset<&str>>(
                    "console",
                    Self::VT_CONSOLE,
                    false,
                )?
                .visit_field::<bool>("debug", Self::VT_DEBUG, false)?
                .finish();
            Ok(())
        }
    }
    pub struct CartInfoArgs<'a> {
        pub api_version_major: u16,
        pub api_version_minor: u16,
        pub title: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub author: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub console: Option<::flatbuffers::WIPOffset<&'a str>>,
        pub debug: bool,
    }
    impl<'a> Default for CartInfoArgs<'a> {
        #[inline]
        fn default() -> Self {
            CartInfoArgs {
                api_version_major: 0,
                api_version_minor: 0,
                title: None,
                author: None,
                console: None,
                debug: false,
            }
        }
    }

    pub struct CartInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CartInfoBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_api_version_major(&mut self, api_version_major: u16) {
            self.fbb_
                .push_slot::<u16>(CartInfo::VT_API_VERSION_MAJOR, api_version_major, 0);
        }
        #[inline]
        pub fn add_api_version_minor(&mut self, api_version_minor: u16) {
            self.fbb_
                .push_slot::<u16>(CartInfo::VT_API_VERSION_MINOR, api_version_minor, 0);
        }
        #[inline]
        pub fn add_title(&mut self, title: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(CartInfo::VT_TITLE, title);
        }
        #[inline]
        pub fn add_author(&mut self, author: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(CartInfo::VT_AUTHOR, author);
        }
        #[inline]
        pub fn add_console(&mut self, console: ::flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<::flatbuffers::WIPOffset<_>>(CartInfo::VT_CONSOLE, console);
        }
        #[inline]
        pub fn add_debug(&mut self, debug: bool) {
            self.fbb_
                .push_slot::<bool>(CartInfo::VT_DEBUG, debug, false);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> CartInfoBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            CartInfoBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<CartInfo<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for CartInfo<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("CartInfo");
            ds.field("api_version_major", &self.api_version_major());
            ds.field("api_version_minor", &self.api_version_minor());
            ds.field("title", &self.title());
            ds.field("author", &self.author());
            ds.field("console", &self.console());
            ds.field("debug", &self.debug());
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `CartInfo`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_cart_info_unchecked`.
    pub fn root_as_cart_info(buf: &[u8]) -> Result<CartInfo<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root::<CartInfo>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `CartInfo` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_cart_info_unchecked`.
    pub fn size_prefixed_root_as_cart_info(
        buf: &[u8],
    ) -> Result<CartInfo<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root::<CartInfo>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `CartInfo` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_cart_info_unchecked`.
    pub fn root_as_cart_info_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<CartInfo<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root_with_opts::<CartInfo<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `CartInfo` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_cart_info_unchecked`.
    pub fn size_prefixed_root_as_cart_info_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<CartInfo<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root_with_opts::<CartInfo<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a CartInfo and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `CartInfo`.
    pub unsafe fn root_as_cart_info_unchecked(buf: &[u8]) -> CartInfo<'_> {
        unsafe { ::flatbuffers::root_unchecked::<CartInfo>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed CartInfo and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `CartInfo`.
    pub unsafe fn size_prefixed_root_as_cart_info_unchecked(buf: &[u8]) -> CartInfo<'_> {
        unsafe { ::flatbuffers::size_prefixed_root_unchecked::<CartInfo>(buf) }
    }
    #[inline]
    pub fn finish_cart_info_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<CartInfo<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_cart_info_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<CartInfo<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod blyt
