// Generated FlatBuffers bindings for the .cart.config section (ADR-0073).
//
// Regenerate after editing schemas/cart_config.fbs with:
//
//     flatc --rust -o devtool/src schemas/cart_config.fbs && cargo fmt -p blyt
//
// (the `cargo fmt` pass is required: CI runs `cargo fmt --check --all`, which
// covers this file, and raw flatc output is not rustfmt-clean.)
// flatc 25.12.19; must stay version-matched with the `flatbuffers` crate in
// devtool/Cargo.toml. The C reader is generated separately by flatcc via the
// CMake custom command — the wire format is identical regardless of codegen.
// NOTE: flatc drops this header on regeneration — re-add it.
//
// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod blyt {

    pub enum CartConfigOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct CartConfig<'a> {
        pub _tab: ::flatbuffers::Table<'a>,
    }

    impl<'a> ::flatbuffers::Follow<'a> for CartConfig<'a> {
        type Inner = CartConfig<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
            }
        }
    }

    impl<'a> CartConfig<'a> {
        pub const VT_FPS: ::flatbuffers::VOffsetT = 4;
        pub const VT_SAVE_VERSION: ::flatbuffers::VOffsetT = 6;
        pub const VT_DEFAULT_PALETTE: ::flatbuffers::VOffsetT = 8;

        #[inline]
        pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
            CartConfig { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: ::flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args CartConfigArgs,
        ) -> ::flatbuffers::WIPOffset<CartConfig<'bldr>> {
            let mut builder = CartConfigBuilder::new(_fbb);
            builder.add_default_palette(args.default_palette);
            builder.add_save_version(args.save_version);
            builder.add_fps(args.fps);
            builder.finish()
        }

        #[inline]
        pub fn fps(&self) -> u8 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u8>(CartConfig::VT_FPS, Some(60)).unwrap() }
        }
        #[inline]
        pub fn save_version(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u32>(CartConfig::VT_SAVE_VERSION, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn default_palette(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u32>(CartConfig::VT_DEFAULT_PALETTE, Some(0))
                    .unwrap()
            }
        }
    }

    impl ::flatbuffers::Verifiable for CartConfig<'_> {
        #[inline]
        fn run_verifier(
            v: &mut ::flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
            v.visit_table(pos)?
                .visit_field::<u8>("fps", Self::VT_FPS, false)?
                .visit_field::<u32>("save_version", Self::VT_SAVE_VERSION, false)?
                .visit_field::<u32>("default_palette", Self::VT_DEFAULT_PALETTE, false)?
                .finish();
            Ok(())
        }
    }
    pub struct CartConfigArgs {
        pub fps: u8,
        pub save_version: u32,
        pub default_palette: u32,
    }
    impl<'a> Default for CartConfigArgs {
        #[inline]
        fn default() -> Self {
            CartConfigArgs {
                fps: 60,
                save_version: 0,
                default_palette: 0,
            }
        }
    }

    pub struct CartConfigBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
        fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CartConfigBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_fps(&mut self, fps: u8) {
            self.fbb_.push_slot::<u8>(CartConfig::VT_FPS, fps, 60);
        }
        #[inline]
        pub fn add_save_version(&mut self, save_version: u32) {
            self.fbb_
                .push_slot::<u32>(CartConfig::VT_SAVE_VERSION, save_version, 0);
        }
        #[inline]
        pub fn add_default_palette(&mut self, default_palette: u32) {
            self.fbb_
                .push_slot::<u32>(CartConfig::VT_DEFAULT_PALETTE, default_palette, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> CartConfigBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            CartConfigBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> ::flatbuffers::WIPOffset<CartConfig<'a>> {
            let o = self.fbb_.end_table(self.start_);
            ::flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl ::core::fmt::Debug for CartConfig<'_> {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            let mut ds = f.debug_struct("CartConfig");
            ds.field("fps", &self.fps());
            ds.field("save_version", &self.save_version());
            ds.field("default_palette", &self.default_palette());
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `CartConfig`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_cart_config_unchecked`.
    pub fn root_as_cart_config(
        buf: &[u8],
    ) -> Result<CartConfig<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root::<CartConfig>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `CartConfig` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_cart_config_unchecked`.
    pub fn size_prefixed_root_as_cart_config(
        buf: &[u8],
    ) -> Result<CartConfig<'_>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root::<CartConfig>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `CartConfig` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_cart_config_unchecked`.
    pub fn root_as_cart_config_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<CartConfig<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::root_with_opts::<CartConfig<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `CartConfig` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_cart_config_unchecked`.
    pub fn size_prefixed_root_as_cart_config_with_opts<'b, 'o>(
        opts: &'o ::flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<CartConfig<'b>, ::flatbuffers::InvalidFlatbuffer> {
        ::flatbuffers::size_prefixed_root_with_opts::<CartConfig<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a CartConfig and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `CartConfig`.
    pub unsafe fn root_as_cart_config_unchecked(buf: &[u8]) -> CartConfig<'_> {
        unsafe { ::flatbuffers::root_unchecked::<CartConfig>(buf) }
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed CartConfig and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `CartConfig`.
    pub unsafe fn size_prefixed_root_as_cart_config_unchecked(buf: &[u8]) -> CartConfig<'_> {
        unsafe { ::flatbuffers::size_prefixed_root_unchecked::<CartConfig>(buf) }
    }
    #[inline]
    pub fn finish_cart_config_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<CartConfig<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_cart_config_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
        fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
        root: ::flatbuffers::WIPOffset<CartConfig<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod blyt
