use std::fs;
use std::path::Path;

use crate::build::{discover_rust_libs, find_rust_sdk, find_sdk_include};

/* -------------------------------------------------------------------------
 * Error type
 * ------------------------------------------------------------------------- */

#[derive(Debug)]
pub struct SetupError(String);

impl std::fmt::Display for SetupError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

fn err(msg: impl Into<String>) -> SetupError {
    SetupError(msg.into())
}

/* -------------------------------------------------------------------------
 * blyt setup vscode
 * ------------------------------------------------------------------------- */

/// launch.json for any blyt cart.  All four configs use the `blyt` debug type.
/// F5 starts a debug session; Ctrl+F5 runs without a debugger.
/// Debug (WASM):   cart runs inside a VS Code panel (embedded browser).
/// Debug (native): cart runs in an external SDL2 window.
/// Build / Build (debug): compile the cart without launching it.
const LAUNCH_JSON: &str = "{\n\
    \x20   // Generated by `blyt setup vscode` — safe to edit or delete.\n\
    \x20   // Requires the Blyt VS Code extension (tools/vscode/).\n\
    \x20   // Debug (WASM):   F5 = debug, Ctrl+F5 = run — cart opens in a VS Code panel.\n\
    \x20   // Debug (native): F5 = debug, Ctrl+F5 = run — cart opens in an external SDL2 window.\n\
    \x20   // Build / Build (debug): compile without launching.\n\
    \x20   \"version\": \"0.2.0\",\n\
    \x20   \"configurations\": [\n\
    \x20       {\n\
    \x20           \"name\": \"Debug (WASM)\",\n\
    \x20           \"type\": \"blyt\",\n\
    \x20           \"request\": \"launch\"\n\
    \x20       },\n\
    \x20       {\n\
    \x20           \"name\": \"Debug (native)\",\n\
    \x20           \"type\": \"blyt\",\n\
    \x20           \"request\": \"launch\",\n\
    \x20           \"mode\": \"native\"\n\
    \x20       },\n\
    \x20       {\n\
    \x20           \"name\": \"Build\",\n\
    \x20           \"type\": \"blyt\",\n\
    \x20           \"request\": \"launch\",\n\
    \x20           \"mode\": \"build\"\n\
    \x20       },\n\
    \x20       {\n\
    \x20           \"name\": \"Build (debug)\",\n\
    \x20           \"type\": \"blyt\",\n\
    \x20           \"request\": \"launch\",\n\
    \x20           \"mode\": \"build-debug\"\n\
    \x20       }\n\
    \x20   ]\n\
    }\n";

/// Generate `.vscode/launch.json` for a blyt cart project so that F5 in VS
/// Code launches a debugger.  A single `blyt` config works for every cart;
/// the extension auto-detects Lua vs native and connects the right debugger.
///
/// Pass `force = true` to overwrite an existing file.
pub fn vscode(project_dir: &Path, force: bool) -> Result<(), SetupError> {
    // Validate: must be a blyt cart project.
    if !project_dir.join("blyt.info.yaml").exists() {
        return Err(err(format!(
            "blyt.info.yaml not found in {} — not a blyt cart project",
            project_dir.display()
        )));
    }

    let launch_json = LAUNCH_JSON;

    let vscode_dir = project_dir.join(".vscode");
    let launch_path = vscode_dir.join("launch.json");

    if launch_path.exists() && !force {
        println!(
            "exists: {} (use --force to overwrite)",
            launch_path.display()
        );
        return Ok(());
    }

    fs::create_dir_all(&vscode_dir)
        .and_then(|_| fs::write(&launch_path, launch_json))
        .map_err(|e| err(format!("could not write {}: {e}", launch_path.display())))?;

    println!("wrote:  {}", launch_path.display());

    write_rust_analyzer_settings(project_dir, &vscode_dir)?;
    Ok(())
}

/// For a cart with Rust game code, write `.vscode/settings.json` telling
/// rust-analyzer the same `--config patch` that `blyt build` uses to inject the
/// SDK `blyt` crate (and any `src/lib` Rust crates).  Without it RA cannot
/// resolve `blyt = "0.1"` (it is not on crates.io) and go-to-definition into the
/// SDK crate is broken while editing (issue #48 item 1a).
///
/// settings.json is precious user state, so this only writes when the file is
/// absent; when it exists, the snippet is printed for the user to merge.
fn write_rust_analyzer_settings(project_dir: &Path, vscode_dir: &Path) -> Result<(), SetupError> {
    if !project_dir.join("src/game/rust/Cargo.toml").exists() {
        return Ok(()); // not a Rust cart — nothing to configure
    }

    // Best-effort: the RA config needs the SDK rust crate, but the primary job
    // (launch.json) already succeeded, so a missing SDK only warns.
    let rust_sdk = match find_sdk_include().and_then(|inc| find_rust_sdk(&inc)) {
        Ok(p) => p,
        Err(e) => {
            println!("note: skipped rust-analyzer config (SDK not found: {e})");
            return Ok(());
        }
    };
    let libs = discover_rust_libs(project_dir).map_err(|e| err(e.to_string()))?;

    // One `--config patch.crates-io.<name>.path="<abs>"` pair per crate, JSON
    // string-escaped (the TOML value needs literal quotes around the path).
    let mut patches: Vec<(String, std::path::PathBuf)> = vec![("blyt".to_string(), rust_sdk)];
    patches.extend(libs);
    let arg_lines = patches
        .iter()
        .map(|(name, path)| {
            format!(
                "        \"--config\",\n        \"patch.crates-io.{name}.path=\\\"{}\\\"\"",
                path.display()
            )
        })
        .collect::<Vec<_>>()
        .join(",\n");

    let settings = format!(
        "{{\n\
         \x20   // Generated by `blyt setup vscode` (issue #48).\n\
         \x20   // The blyt SDK crate is injected at build time; give rust-analyzer the\n\
         \x20   // same --config patch so go-to-definition into `blyt` resolves.\n\
         \x20   \"rust-analyzer.linkedProjects\": [\"src/game/rust/Cargo.toml\"],\n\
         \x20   \"rust-analyzer.cargo.extraArgs\": [\n\
         {arg_lines}\n\
         \x20   ]\n\
         }}\n"
    );

    let settings_path = vscode_dir.join("settings.json");
    if settings_path.exists() {
        println!(
            "exists: {} — add this rust-analyzer config manually:\n{}",
            settings_path.display(),
            settings
        );
        return Ok(());
    }
    fs::create_dir_all(vscode_dir)
        .and_then(|_| fs::write(&settings_path, &settings))
        .map_err(|e| err(format!("could not write {}: {e}", settings_path.display())))?;
    println!("wrote:  {}", settings_path.display());
    Ok(())
}
