use std::fs;
use std::path::Path;

/* -------------------------------------------------------------------------
 * Error type
 * ------------------------------------------------------------------------- */

#[derive(Debug)]
pub struct SetupError(String);

impl std::fmt::Display for SetupError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

fn err(msg: impl Into<String>) -> SetupError {
    SetupError(msg.into())
}

/* -------------------------------------------------------------------------
 * blyt setup vscode
 * ------------------------------------------------------------------------- */

/// launch.json for any blyt cart.  All four configs use the `blyt` debug type.
/// F5 starts a debug session; Ctrl+F5 runs without a debugger.
/// Debug (WASM):   cart runs inside a VS Code panel (embedded browser).
/// Debug (native): cart runs in an external SDL2 window.
/// Build / Build (debug): compile the cart without launching it.
const LAUNCH_JSON: &str = "{\n\
    \x20   // Generated by `blyt setup vscode` — safe to edit or delete.\n\
    \x20   // Requires the Blyt VS Code extension (tools/vscode/).\n\
    \x20   // Debug (WASM):   F5 = debug, Ctrl+F5 = run — cart opens in a VS Code panel.\n\
    \x20   // Debug (native): F5 = debug, Ctrl+F5 = run — cart opens in an external SDL2 window.\n\
    \x20   // Build / Build (debug): compile without launching.\n\
    \x20   \"version\": \"0.2.0\",\n\
    \x20   \"configurations\": [\n\
    \x20       {\n\
    \x20           \"name\": \"Debug (WASM)\",\n\
    \x20           \"type\": \"blyt\",\n\
    \x20           \"request\": \"launch\"\n\
    \x20       },\n\
    \x20       {\n\
    \x20           \"name\": \"Debug (native)\",\n\
    \x20           \"type\": \"blyt\",\n\
    \x20           \"request\": \"launch\",\n\
    \x20           \"mode\": \"native\"\n\
    \x20       },\n\
    \x20       {\n\
    \x20           \"name\": \"Build\",\n\
    \x20           \"type\": \"blyt\",\n\
    \x20           \"request\": \"launch\",\n\
    \x20           \"mode\": \"build\"\n\
    \x20       },\n\
    \x20       {\n\
    \x20           \"name\": \"Build (debug)\",\n\
    \x20           \"type\": \"blyt\",\n\
    \x20           \"request\": \"launch\",\n\
    \x20           \"mode\": \"build-debug\"\n\
    \x20       }\n\
    \x20   ]\n\
    }\n";

/// Generate `.vscode/launch.json` for a blyt cart project so that F5 in VS
/// Code launches a debugger.  A single `blyt` config works for every cart;
/// the extension auto-detects Lua vs native and connects the right debugger.
///
/// Pass `force = true` to overwrite an existing file.
pub fn vscode(project_dir: &Path, force: bool) -> Result<(), SetupError> {
    // Validate: must be a blyt cart project.
    if !project_dir.join("blyt.info.yaml").exists() {
        return Err(err(format!(
            "blyt.info.yaml not found in {} — not a blyt cart project",
            project_dir.display()
        )));
    }

    let launch_json = LAUNCH_JSON;

    let vscode_dir = project_dir.join(".vscode");
    let launch_path = vscode_dir.join("launch.json");

    if launch_path.exists() && !force {
        println!(
            "exists: {} (use --force to overwrite)",
            launch_path.display()
        );
        return Ok(());
    }

    fs::create_dir_all(&vscode_dir)
        .and_then(|_| fs::write(&launch_path, launch_json))
        .map_err(|e| err(format!("could not write {}: {e}", launch_path.display())))?;

    println!("wrote:  {}", launch_path.display());
    Ok(())
}
