use std::fs;
use std::path::Path;

/* -------------------------------------------------------------------------
 * Error type
 * ------------------------------------------------------------------------- */

#[derive(Debug)]
pub struct SetupError(String);

impl std::fmt::Display for SetupError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

fn err(msg: impl Into<String>) -> SetupError {
    SetupError(msg.into())
}

/* -------------------------------------------------------------------------
 * blyt setup vscode
 * ------------------------------------------------------------------------- */

/// launch.json for a Lua cart: Lua DAP debugger + native GDB debugger.
const LAUNCH_JSON_LUA: &str = "{\n\
    \x20   // Generated by `blyt setup vscode` — safe to edit or delete.\n\
    \x20   // Requires the Blyt VS Code extension (tools/vscode/).\n\
    \x20   \"version\": \"0.2.0\",\n\
    \x20   \"configurations\": [\n\
    \x20       {\n\
    \x20           \"name\": \"Debug Lua\",\n\
    \x20           \"type\": \"blyt-lua\",\n\
    \x20           \"request\": \"launch\"\n\
    \x20       },\n\
    \x20       {\n\
    \x20           \"name\": \"Debug Native (GDB)\",\n\
    \x20           \"type\": \"blyt-native-gdb\",\n\
    \x20           \"request\": \"launch\"\n\
    \x20       }\n\
    \x20   ]\n\
    }\n";

/// launch.json for a non-Lua cart: native GDB debugger only.
const LAUNCH_JSON_NATIVE: &str = "{\n\
    \x20   // Generated by `blyt setup vscode` — safe to edit or delete.\n\
    \x20   // Requires the Blyt VS Code extension (tools/vscode/).\n\
    \x20   \"version\": \"0.2.0\",\n\
    \x20   \"configurations\": [\n\
    \x20       {\n\
    \x20           \"name\": \"Debug Native (GDB)\",\n\
    \x20           \"type\": \"blyt-native-gdb\",\n\
    \x20           \"request\": \"launch\"\n\
    \x20       }\n\
    \x20   ]\n\
    }\n";

/// Generate `.vscode/launch.json` for a blyt cart project so that F5 in VS
/// Code launches a debugger.  Lua carts get both a Lua DAP entry and a native
/// GDB entry; all other carts get a native GDB entry.
///
/// Pass `force = true` to overwrite an existing file.
pub fn vscode(project_dir: &Path, force: bool) -> Result<(), SetupError> {
    // Validate: must be a blyt cart project.
    if !project_dir.join("blyt.info.yaml").exists() {
        return Err(err(format!(
            "blyt.info.yaml not found in {} — not a blyt cart project",
            project_dir.display()
        )));
    }

    let is_lua = project_dir.join("src/game/lua").exists();
    let launch_json = if is_lua {
        LAUNCH_JSON_LUA
    } else {
        LAUNCH_JSON_NATIVE
    };

    let vscode_dir = project_dir.join(".vscode");
    let launch_path = vscode_dir.join("launch.json");

    if launch_path.exists() && !force {
        println!(
            "exists: {} (use --force to overwrite)",
            launch_path.display()
        );
        return Ok(());
    }

    fs::create_dir_all(&vscode_dir)
        .and_then(|_| fs::write(&launch_path, launch_json))
        .map_err(|e| err(format!("could not write {}: {e}", launch_path.display())))?;

    println!("wrote:  {}", launch_path.display());
    Ok(())
}
