#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "blyt_runtime.h"
#include "libretro.h"

/* -------------------------------------------------------------------------
 * Embedded guest libraries (generated by cmake/bin2c.py from the built .so
 * files, then compiled into this core).  The core registers them at init so
 * dynlink can load them from memory — no BLYT_LIB_DIR or filesystem access
 * required when running inside a libretro frontend.
 * ------------------------------------------------------------------------- */

/* Embedded guest library blobs — only present when BLYT_EMBED_LIBS is defined
 * (i.e. when building the standalone libretro .so via cmake/blyt_sdk.cmake).
 * When blyt_libretro.c is compiled into blytplay without embedding, dynlink
 * falls back to BLYT_LIB_DIR as usual. */
#ifdef BLYT_EMBED_LIBS
extern const unsigned char blytcommon_so[];
extern const unsigned int blytcommon_so_len;
extern const unsigned char blytc_so[];
extern const unsigned int blytc_so_len;
extern const unsigned char blyt32_so[];
extern const unsigned int blyt32_so_len;
#ifdef BLYT_EMBED_LUA
extern const unsigned char blyt32lua_so[];
extern const unsigned int blyt32lua_so_len;
#endif /* BLYT_EMBED_LUA */
#endif /* BLYT_EMBED_LIBS */

/* -------------------------------------------------------------------------
 * Frontend callbacks (set before retro_init by the frontend)
 * ------------------------------------------------------------------------- */

static retro_environment_t g_env_cb = NULL;
static retro_video_refresh_t g_video_cb = NULL;
static retro_audio_sample_t g_audio_cb = NULL;
static retro_audio_sample_batch_t g_audio_batch_cb = NULL;
static retro_input_poll_t g_input_poll_cb = NULL;
static retro_input_state_t g_input_state_cb = NULL;
static retro_log_printf_t g_log_cb = NULL;

/* -------------------------------------------------------------------------
 * Cart and session state
 * ------------------------------------------------------------------------- */

static blyt_cart_t *g_cart = NULL;
static blyt_session_t *g_session = NULL;
static bool g_cart_done = false;
static blyt_cart_run_err_t g_run_err = BLYT_RUN_OK;
static bool g_dap_active = false;
/* Path the current cart was loaded from — used by the dev control hot reload
 * (issue #87) to reopen the freshly rebuilt cart from disk. */
static char *g_cart_path = NULL;

/* XRGB8888 expansion buffer — filled by blyt_session_expand_frame() each
 * frame and passed to the frontend video callback. */
static uint32_t g_xrgb[BLYT_FRAME_W * BLYT_FRAME_H];

/* -------------------------------------------------------------------------
 * Log callback passed to libblyt — routes blyt_console_debug to retro_log
 * ------------------------------------------------------------------------- */

static void libretro_log(const char *msg) {
    if (g_log_cb)
        g_log_cb(RETRO_LOG_INFO, "%s\n", msg);
    else
        fprintf(stderr, "[blyt] %s\n", msg);
}

/* =========================================================================
 * Required libretro entry points
 * ========================================================================= */

RETRO_API unsigned retro_api_version(void) {
    return RETRO_API_VERSION;
}

RETRO_API void retro_set_environment(retro_environment_t cb) {
    g_env_cb = cb;

    /* Request the log interface as early as possible */
    struct retro_log_callback log_cb;
    if (cb(RETRO_ENVIRONMENT_GET_LOG_INTERFACE, &log_cb))
        g_log_cb = log_cb.log;

    /* Declare pixel format (XRGB8888 — reserved for when graphics land) */
    enum retro_pixel_format fmt = RETRO_PIXEL_FORMAT_XRGB8888;
    cb(RETRO_ENVIRONMENT_SET_PIXEL_FORMAT, &fmt);
}

RETRO_API void retro_set_video_refresh(retro_video_refresh_t cb) {
    g_video_cb = cb;
}

RETRO_API void retro_set_audio_sample(retro_audio_sample_t cb) {
    g_audio_cb = cb;
}

RETRO_API void retro_set_audio_sample_batch(retro_audio_sample_batch_t cb) {
    g_audio_batch_cb = cb;
}

RETRO_API void retro_set_input_poll(retro_input_poll_t cb) {
    g_input_poll_cb = cb;
}

RETRO_API void retro_set_input_state(retro_input_state_t cb) {
    g_input_state_cb = cb;
}

RETRO_API void retro_init(void) {
#ifdef BLYT_EMBED_LIBS
    blyt_register_lib("libblytcommon.so", blytcommon_so, blytcommon_so_len);
    blyt_register_lib("libblytc.so", blytc_so, blytc_so_len);
    blyt_register_lib("libblyt32.so", blyt32_so, blyt32_so_len);
#ifdef BLYT_EMBED_LUA
    blyt_register_lib("libblyt32lua.so", blyt32lua_so, blyt32lua_so_len);
#endif
#endif
}

RETRO_API void retro_deinit(void) {
    blyt_clear_libs();
}

RETRO_API void retro_get_system_info(struct retro_system_info *info) {
    memset(info, 0, sizeof(*info));
    info->library_name = "blyt";
    info->library_version = blyt_runtime_version();
    info->valid_extensions = "blyt";
    info->need_fullpath = true;
    info->block_extract = false;
}

RETRO_API void retro_get_system_av_info(struct retro_system_av_info *info) {
    memset(info, 0, sizeof(*info));
    info->geometry.base_width = BLYT_FRAME_W;
    info->geometry.base_height = BLYT_FRAME_H;
    info->geometry.max_width = BLYT_FRAME_W;
    info->geometry.max_height = BLYT_FRAME_H;
    info->geometry.aspect_ratio = 4.0f / 3.0f;
    info->timing.fps = 60.0;
    info->timing.sample_rate = 44100.0;
}

RETRO_API void retro_set_controller_port_device(unsigned port, unsigned device) {
    (void)port;
    (void)device;
}

RETRO_API bool retro_load_game(const struct retro_game_info *game) {
    if (!game || !game->path) {
        if (g_log_cb)
            g_log_cb(RETRO_LOG_ERROR, "blyt: no cart path provided\n");
        return false;
    }

    blyt_cart_err_t err = blyt_cart_open(game->path, &g_cart);
    if (err != BLYT_CART_OK) {
        if (g_log_cb)
            g_log_cb(RETRO_LOG_ERROR, "blyt: failed to load cart: %s\n", blyt_cart_err_str(err));
        g_cart = NULL;
        return false;
    }

    /* Remember the path so the dev control hot reload can reopen it. */
    free(g_cart_path);
    g_cart_path = strdup(game->path);

    fprintf(stderr, "Blyt %s - %s (%s %s)\n", blyt_runtime_version(), blyt_cart_title(g_cart),
            blyt_cart_id(g_cart), blyt_cart_version(g_cart));

    g_session = blyt_session_create(g_cart, libretro_log);
    if (!g_session) {
        if (g_log_cb)
            g_log_cb(RETRO_LOG_ERROR, "blyt: failed to create session\n");
        blyt_cart_close(g_cart);
        g_cart = NULL;
        return false;
    }

#ifdef BLYT_DAP
    {
        const char *dap_port_str = getenv("BLYT_DAP_PORT");
        if (dap_port_str) {
            /* DAP only applies to Lua carts — the DAP hook lives in
             * libblyt32lua.so which is not loaded for C carts. */
            size_t lua_sec_size;
            bool is_lua = blyt_cart_find_section(g_cart, ".cart.lua", &lua_sec_size) != NULL;
            if (is_lua) {
                int dap_port = atoi(dap_port_str);
                int actual_port = 0;
                if (blyt_session_dap_listen(g_session, &actual_port) >= 0) {
                    g_dap_active = true;
                    if (g_log_cb)
                        g_log_cb(RETRO_LOG_INFO, "blyt: DAP listening on port %d\n", actual_port);
                    else
                        fprintf(stderr, "blyt: DAP listening on port %d\n", actual_port);
                }
                (void)dap_port;
            }
        }
    }
#endif
#ifdef BLYT_GDB
    {
        const char *gdb_port_str = getenv("BLYT_GDB_PORT");
        if (gdb_port_str) {
            int gdb_port = atoi(gdb_port_str);
            int actual_port = gdb_port;
            if (blyt_session_gdb_listen(g_session, &actual_port) >= 0) {
                if (g_log_cb)
                    g_log_cb(RETRO_LOG_INFO, "blyt: GDB listening on port %d\n", actual_port);
                else
                    fprintf(stderr, "blyt: GDB listening on port %d\n", actual_port);
            }
        }
    }
#endif

    g_cart_done = false;
    return true;
}

RETRO_API bool retro_load_game_special(unsigned type, const struct retro_game_info *info,
                                       size_t num_info) {
    (void)type;
    (void)info;
    (void)num_info;
    return false;
}

RETRO_API void retro_unload_game(void) {
    g_dap_active = false;
#ifdef BLYT_DAP
    if (g_session)
        blyt_session_dap_shutdown(g_session);
#endif
#ifdef BLYT_GDB
    if (g_session)
        blyt_session_gdb_shutdown(g_session);
#endif
    blyt_session_destroy(g_session);
    g_session = NULL;
    blyt_cart_close(g_cart);
    g_cart = NULL;
    free(g_cart_path);
    g_cart_path = NULL;
    g_cart_done = false;
    g_run_err = BLYT_RUN_OK;
}

RETRO_API void retro_reset(void) {
    blyt_session_destroy(g_session);
    g_session = g_cart ? blyt_session_create(g_cart, libretro_log) : NULL;
    if (!g_session && g_log_cb)
        g_log_cb(RETRO_LOG_ERROR, "blyt: reset failed to recreate the cart session\n");
    g_cart_done = false;
    g_run_err = BLYT_RUN_OK;
}

RETRO_API void retro_run(void) {
    if (g_input_poll_cb)
        g_input_poll_cb();

    if (!g_cart_done && g_session) {
        blyt_cart_run_err_t err = blyt_session_run_frame(g_session);
        if (err == BLYT_RUN_FRAME_DONE) {
            /* normal frame */
        } else if (err == BLYT_RUN_RESTART) {
            /* DAP restart: recreate session, reattach DAP, wait for reconfiguration. */
            retro_reset();
#ifdef BLYT_DAP
            if (g_dap_active && g_session) {
                blyt_session_dap_reattach(g_session);
                blyt_session_dap_wait_ready(g_session);
            }
#endif
        } else {
            g_cart_done = true;
            g_run_err = err;
            if (err == BLYT_RUN_ERR_ECALL_TRAP && g_log_cb)
                g_log_cb(RETRO_LOG_ERROR, "blyt: cart attempted a non-permitted ecall\n");
            else if (err == BLYT_RUN_ERR_ABORT && g_log_cb)
                g_log_cb(RETRO_LOG_ERROR, "blyt: cart aborted\n");
        }
    }

    if (g_video_cb && g_session) {
        blyt_session_expand_frame(g_session, g_xrgb);
        g_video_cb(g_xrgb, BLYT_FRAME_W, BLYT_FRAME_H, BLYT_FRAME_W * (uint32_t)sizeof(uint32_t));
    }
}

RETRO_API size_t retro_serialize_size(void) {
    return 0;
}

RETRO_API bool retro_serialize(void *data, size_t size) {
    (void)data;
    (void)size;
    return false;
}

RETRO_API bool retro_unserialize(const void *data, size_t size) {
    (void)data;
    (void)size;
    return false;
}

RETRO_API void retro_cheat_reset(void) {
}

RETRO_API void retro_cheat_set(unsigned index, bool enabled, const char *code) {
    (void)index;
    (void)enabled;
    (void)code;
}

RETRO_API unsigned retro_get_region(void) {
    return RETRO_REGION_NTSC;
}

RETRO_API void *retro_get_memory_data(unsigned id) {
    (void)id;
    return NULL;
}

RETRO_API size_t retro_get_memory_size(unsigned id) {
    (void)id;
    return 0;
}

/* Used by the SDL frontend when linked directly (not via dlopen) to detect
 * when the cart has exited and the run loop should stop. */
bool blyt_libretro_is_done(void) {
    return g_cart_done;
}

#ifdef BLYT_DAP
/* Block until the DAP client sends configurationDone (breakpoints set) or the
 * server shuts down.  Called by the SDL frontend before starting the game loop. */
bool blyt_libretro_dap_wait_ready(void) {
    return g_session && blyt_session_dap_wait_ready(g_session) != 0;
}
#endif

#ifdef BLYT_GDB
/* Block until a GDB client connects.  Called by the SDL frontend before
 * starting the game loop so the cart does not run past any early breakpoints. */
bool blyt_libretro_gdb_wait_attached(void) {
    return g_session && blyt_session_gdb_wait_attached(g_session) != 0;
}

/* In hybrid (DAP+GDB) mode, clear the initial GDB halt so the cart can run
 * without waiting for a vCont;c from lldb-dap.  The Lua DAP session has
 * already registered its breakpoints by the time this is called. */
void blyt_libretro_gdb_continue_initial_halt(void) {
    if (g_session)
        blyt_session_gdb_continue_initial_halt(g_session);
}
#endif

blyt_cart_run_err_t blyt_libretro_run_err(void) {
    return g_run_err;
}

void retro_reset_every_frame_cycle(void) {
    if (g_session)
        blyt_reset_every_frame_cycle(g_session);
}

/* -------------------------------------------------------------------------
 * Dev control channel operations (issue #87)
 *
 * Driven by the SDL frontend's dev control server.  reset is the standard
 * retro_reset(); save/load persist to disk slots; reload swaps in the freshly
 * rebuilt cart from disk while preserving state buffers (ADR-0045).
 * ------------------------------------------------------------------------- */

/* Dev control reset: recreate the session AND run the boot frame so init()
 * executes immediately, leaving the cart in its post-init initial state — the
 * same state a fresh load reaches before the first dev control command.
 *
 * retro_reset() alone defers init() to the next retro_run(), so a save_state or
 * load_state issued right after reset (before the player loop services another
 * frame) would observe a pre-init blank: no slots allocated, score zeroed.  The
 * dev control poll loop drains every buffered command in one pass with no frame
 * in between, so under load a reset+save_state pair races init() and the save
 * captures empty state (issue #105).  Booting here closes that race.  This is
 * the same explicit boot blyt_libretro_reload() runs after swapping the cart. */
void blyt_libretro_reset(void) {
    retro_reset();
    if (g_session)
        blyt_session_run_frame(g_session);
}

bool blyt_libretro_save_state(uint32_t slot) {
    return g_session && blyt_session_save_state(g_session, slot) == 0;
}

bool blyt_libretro_load_state(uint32_t slot) {
    return g_session && blyt_session_load_state(g_session, slot) == 0;
}

bool blyt_libretro_reload(void) {
    blyt_state_snapshot_t *snap;
    blyt_cart_err_t err;

    if (!g_session || !g_cart_path)
        return false;

    /* In-VM cart-as-library module swap (issue #127, spike-W β / gate G1): swap
     * the cart's code IN PLACE rather than destroying and recreating the session.
     * The rv32 VM, libblyt32/libblyt32lua and the per-session debug state all
     * stay alive — sidestepping the rv32emu single-VM-per-process global-state
     * hazard a session recreate crosses (issue #44) — and the dev-control/debug
     * connection survives the reload.  State is preserved across the swap exactly
     * as before (snapshot → swap → boot → restore(HOT_RELOAD)). */

    /* 1. Snapshot live state (flushing transient state via on_save_state). */
    snap = blyt_session_snapshot(g_session);

    /* 2. Open the freshly rebuilt cart from disk. */
    blyt_cart_t *new_cart = NULL;
    err = blyt_cart_open(g_cart_path, &new_cart);
    if (err != BLYT_CART_OK) {
        if (g_log_cb)
            g_log_cb(RETRO_LOG_ERROR, "blyt: reload failed to open cart: %s\n",
                     blyt_cart_err_str(err));
        blyt_session_snapshot_free(snap);
        return false; /* old session keeps running the old code */
    }

    /* 3. Swap the cart image into the live session (same base, run-mode — the
     *    GDB solib reload event lives in the debug layer, #119). */
    if (!blyt_session_swap_cart(g_session, new_cart, 0u, NULL)) {
        if (g_log_cb)
            g_log_cb(RETRO_LOG_ERROR, "blyt: reload failed to swap cart module\n");
        blyt_cart_close(new_cart);
        blyt_session_snapshot_free(snap);
        return false; /* old session keeps running the old code */
    }

    /* 4. The session now reads its sections/resources from the new cart; retire
     *    the old handle and keep the new one as the session's cart. */
    blyt_cart_close(g_cart);
    g_cart = new_cart;
    g_cart_done = false;
    g_run_err = BLYT_RUN_OK;

    /* 5. Run the first frame so the new cart's init() executes and allocates its
     *    state slots, then restore the snapshot over the fresh buffers and notify
     *    the cart via on_load_state(HOT_RELOAD).  The discarded frame is never
     *    presented. */
    blyt_session_run_frame(g_session);
    blyt_session_restore(g_session, snap, 3u /* BLYT_LOAD_HOT_RELOAD */);
    return true;
}

/* Hot-swap edited assets without a VM restart (issue #91): re-read the resource
 * table from the (already rebuilt) staging directory.  Applied between frames by
 * the dev-control `update_assets` command; the next frame sees the new bytes.
 * `ids`/`n` are the changed resource ids: after the table swap the cart's
 * optional on_assets_reloaded hook is invoked with them (issue #122) so a cart
 * that cached/derived from a resource can re-derive only the affected ones. */
bool blyt_libretro_update_assets(const uint32_t *ids, size_t n) {
    if (!g_session)
        return false;
    if (!blyt_session_reload_resources(g_session, g_cart))
        return false;
    blyt_session_notify_assets_reloaded(g_session, ids, n);
    return true;
}
