#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "blyt_runtime.h"
#include "libretro.h"

/* -------------------------------------------------------------------------
 * Embedded guest libraries (generated by cmake/bin2c.py from the built .so
 * files, then compiled into this core).  The core registers them at init so
 * dynlink can load them from memory — no BLYT_LIB_DIR or filesystem access
 * required when running inside a libretro frontend.
 * ------------------------------------------------------------------------- */

/* Embedded guest library blobs — only present when BLYT_EMBED_LIBS is defined
 * (i.e. when building the standalone libretro .so via cmake/blyt_sdk.cmake).
 * When blyt_libretro.c is compiled into blytrun without embedding, dynlink
 * falls back to BLYT_LIB_DIR as usual. */
#ifdef BLYT_EMBED_LIBS
extern const unsigned char blytcommon_so[];
extern const unsigned int blytcommon_so_len;
extern const unsigned char blytc_so[];
extern const unsigned int blytc_so_len;
extern const unsigned char blyt32_so[];
extern const unsigned int blyt32_so_len;
#ifdef BLYT_EMBED_LUA
extern const unsigned char blyt32lua_so[];
extern const unsigned int blyt32lua_so_len;
#endif /* BLYT_EMBED_LUA */
#endif /* BLYT_EMBED_LIBS */

/* -------------------------------------------------------------------------
 * Frontend callbacks (set before retro_init by the frontend)
 * ------------------------------------------------------------------------- */

static retro_environment_t g_env_cb = NULL;
static retro_video_refresh_t g_video_cb = NULL;
static retro_audio_sample_t g_audio_cb = NULL;
static retro_audio_sample_batch_t g_audio_batch_cb = NULL;
static retro_input_poll_t g_input_poll_cb = NULL;
static retro_input_state_t g_input_state_cb = NULL;
static retro_log_printf_t g_log_cb = NULL;

/* -------------------------------------------------------------------------
 * Cart and session state
 * ------------------------------------------------------------------------- */

static blyt_cart_t *g_cart = NULL;
static blyt_session_t *g_session = NULL;
static bool g_cart_done = false;
static blyt_cart_run_err_t g_run_err = BLYT_RUN_OK;

/* XRGB8888 expansion buffer — filled by blyt_session_expand_frame() each
 * frame and passed to the frontend video callback. */
static uint32_t g_xrgb[BLYT_FRAME_W * BLYT_FRAME_H];

/* -------------------------------------------------------------------------
 * Log callback passed to libblyt — routes blyt_console_debug to retro_log
 * ------------------------------------------------------------------------- */

static void libretro_log(const char *msg) {
    if (g_log_cb)
        g_log_cb(RETRO_LOG_INFO, "%s\n", msg);
    else
        fprintf(stderr, "[blyt] %s\n", msg);
}

/* =========================================================================
 * Required libretro entry points
 * ========================================================================= */

RETRO_API unsigned retro_api_version(void) {
    return RETRO_API_VERSION;
}

RETRO_API void retro_set_environment(retro_environment_t cb) {
    g_env_cb = cb;

    /* Request the log interface as early as possible */
    struct retro_log_callback log_cb;
    if (cb(RETRO_ENVIRONMENT_GET_LOG_INTERFACE, &log_cb))
        g_log_cb = log_cb.log;

    /* Declare pixel format (XRGB8888 — reserved for when graphics land) */
    enum retro_pixel_format fmt = RETRO_PIXEL_FORMAT_XRGB8888;
    cb(RETRO_ENVIRONMENT_SET_PIXEL_FORMAT, &fmt);
}

RETRO_API void retro_set_video_refresh(retro_video_refresh_t cb) {
    g_video_cb = cb;
}

RETRO_API void retro_set_audio_sample(retro_audio_sample_t cb) {
    g_audio_cb = cb;
}

RETRO_API void retro_set_audio_sample_batch(retro_audio_sample_batch_t cb) {
    g_audio_batch_cb = cb;
}

RETRO_API void retro_set_input_poll(retro_input_poll_t cb) {
    g_input_poll_cb = cb;
}

RETRO_API void retro_set_input_state(retro_input_state_t cb) {
    g_input_state_cb = cb;
}

RETRO_API void retro_init(void) {
#ifdef BLYT_EMBED_LIBS
    blyt_register_lib("libblytcommon.so", blytcommon_so, blytcommon_so_len);
    blyt_register_lib("libblytc.so", blytc_so, blytc_so_len);
    blyt_register_lib("libblyt32.so", blyt32_so, blyt32_so_len);
#ifdef BLYT_EMBED_LUA
    blyt_register_lib("libblyt32lua.so", blyt32lua_so, blyt32lua_so_len);
#endif
#endif
}

RETRO_API void retro_deinit(void) {
    blyt_clear_libs();
}

RETRO_API void retro_get_system_info(struct retro_system_info *info) {
    memset(info, 0, sizeof(*info));
    info->library_name = "blyt";
    info->library_version = BLYT_VERSION;
    info->valid_extensions = "blyt";
    info->need_fullpath = true;
    info->block_extract = false;
}

RETRO_API void retro_get_system_av_info(struct retro_system_av_info *info) {
    memset(info, 0, sizeof(*info));
    info->geometry.base_width = BLYT_FRAME_W;
    info->geometry.base_height = BLYT_FRAME_H;
    info->geometry.max_width = BLYT_FRAME_W;
    info->geometry.max_height = BLYT_FRAME_H;
    info->geometry.aspect_ratio = 4.0f / 3.0f;
    info->timing.fps = 60.0;
    info->timing.sample_rate = 44100.0;
}

RETRO_API void retro_set_controller_port_device(unsigned port, unsigned device) {
    (void)port;
    (void)device;
}

RETRO_API bool retro_load_game(const struct retro_game_info *game) {
    if (!game || !game->path) {
        if (g_log_cb)
            g_log_cb(RETRO_LOG_ERROR, "blyt: no cart path provided\n");
        return false;
    }

    blyt_cart_err_t err = blyt_cart_open(game->path, &g_cart);
    if (err != BLYT_CART_OK) {
        if (g_log_cb)
            g_log_cb(RETRO_LOG_ERROR, "blyt: failed to load cart: %s\n", blyt_cart_err_str(err));
        g_cart = NULL;
        return false;
    }

    g_session = blyt_session_create(g_cart, libretro_log);
    if (!g_session) {
        if (g_log_cb)
            g_log_cb(RETRO_LOG_ERROR, "blyt: failed to create session\n");
        blyt_cart_close(g_cart);
        g_cart = NULL;
        return false;
    }

#ifdef BLYT_DAP
    {
        const char *dap_port_str = getenv("BLYT_DAP_PORT");
        if (dap_port_str) {
            /* DAP only applies to Lua carts — the DAP hook lives in
             * libblyt32lua.so which is not loaded for C carts. */
            size_t lua_sec_size;
            bool is_lua = blyt_cart_find_section(g_cart, ".cart.lua", &lua_sec_size) != NULL;
            if (is_lua) {
                int dap_port = atoi(dap_port_str);
                int actual_port = 0;
                if (blyt_session_dap_listen(g_session, &actual_port) >= 0) {
                    if (g_log_cb)
                        g_log_cb(RETRO_LOG_INFO, "blyt: DAP listening on port %d\n", actual_port);
                    else
                        fprintf(stderr, "blyt: DAP listening on port %d\n", actual_port);
                }
                (void)dap_port;
            }
        }
    }
#endif
#ifdef BLYT_GDB
    {
        const char *gdb_port_str = getenv("BLYT_GDB_PORT");
        if (gdb_port_str) {
            int gdb_port = atoi(gdb_port_str);
            int actual_port = gdb_port;
            if (blyt_session_gdb_listen(g_session, &actual_port) >= 0) {
                if (g_log_cb)
                    g_log_cb(RETRO_LOG_INFO, "blyt: GDB listening on port %d\n", actual_port);
                else
                    fprintf(stderr, "blyt: GDB listening on port %d\n", actual_port);
            }
        }
    }
#endif

    g_cart_done = false;
    return true;
}

RETRO_API bool retro_load_game_special(unsigned type, const struct retro_game_info *info,
                                       size_t num_info) {
    (void)type;
    (void)info;
    (void)num_info;
    return false;
}

RETRO_API void retro_unload_game(void) {
#ifdef BLYT_DAP
    if (g_session)
        blyt_session_dap_shutdown(g_session);
#endif
#ifdef BLYT_GDB
    if (g_session)
        blyt_session_gdb_shutdown(g_session);
#endif
    blyt_session_destroy(g_session);
    g_session = NULL;
    blyt_cart_close(g_cart);
    g_cart = NULL;
    g_cart_done = false;
    g_run_err = BLYT_RUN_OK;
}

RETRO_API void retro_reset(void) {
    blyt_session_destroy(g_session);
    g_session = g_cart ? blyt_session_create(g_cart, libretro_log) : NULL;
    g_cart_done = false;
    g_run_err = BLYT_RUN_OK;
}

RETRO_API void retro_run(void) {
    if (g_input_poll_cb)
        g_input_poll_cb();

    if (!g_cart_done && g_session) {
        blyt_cart_run_err_t err = blyt_session_run_frame(g_session);
        if (err != BLYT_RUN_FRAME_DONE) {
            g_cart_done = true;
            g_run_err = err;
            if (err == BLYT_RUN_ERR_ECALL_TRAP && g_log_cb)
                g_log_cb(RETRO_LOG_ERROR, "blyt: cart attempted a non-permitted ecall\n");
            else if (err == BLYT_RUN_ERR_ABORT && g_log_cb)
                g_log_cb(RETRO_LOG_ERROR, "blyt: cart aborted\n");
        }
    }

    if (g_video_cb && g_session) {
        blyt_session_expand_frame(g_session, g_xrgb);
        g_video_cb(g_xrgb, BLYT_FRAME_W, BLYT_FRAME_H, BLYT_FRAME_W * (uint32_t)sizeof(uint32_t));
    }
}

RETRO_API size_t retro_serialize_size(void) {
    return 0;
}

RETRO_API bool retro_serialize(void *data, size_t size) {
    (void)data;
    (void)size;
    return false;
}

RETRO_API bool retro_unserialize(const void *data, size_t size) {
    (void)data;
    (void)size;
    return false;
}

RETRO_API void retro_cheat_reset(void) {
}

RETRO_API void retro_cheat_set(unsigned index, bool enabled, const char *code) {
    (void)index;
    (void)enabled;
    (void)code;
}

RETRO_API unsigned retro_get_region(void) {
    return RETRO_REGION_NTSC;
}

RETRO_API void *retro_get_memory_data(unsigned id) {
    (void)id;
    return NULL;
}

RETRO_API size_t retro_get_memory_size(unsigned id) {
    (void)id;
    return 0;
}

/* Used by the SDL frontend when linked directly (not via dlopen) to detect
 * when the cart has exited and the run loop should stop. */
bool blyt_libretro_is_done(void) {
    return g_cart_done;
}

#ifdef BLYT_DAP
/* Block until the DAP client sends configurationDone (breakpoints set) or the
 * server shuts down.  Called by the SDL frontend before starting the game loop. */
bool blyt_libretro_dap_wait_ready(void) {
    return g_session && blyt_session_dap_wait_ready(g_session) != 0;
}
#endif

#ifdef BLYT_GDB
/* Block until a GDB client connects.  Called by the SDL frontend before
 * starting the game loop so the cart does not run past any early breakpoints. */
bool blyt_libretro_gdb_wait_attached(void) {
    return g_session && blyt_session_gdb_wait_attached(g_session) != 0;
}
#endif

blyt_cart_run_err_t blyt_libretro_run_err(void) {
    return g_run_err;
}
