use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/* -------------------------------------------------------------------------
 * .cart.info section data
 *
 * 8-byte preamble (ADR-0073): "CINF" + format_major(u16le=0) + format_minor(u16le=0)
 * followed by the FlatBuffers CartInfo table with api_version_major=0 and
 * api_version_minor=0 (12 bytes as produced by flatcc for this schema).
 * ------------------------------------------------------------------------- */
const CART_INFO: &[u8] = &[
    b'C', b'I', b'N', b'F', 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0xfc, 0xff, 0xff, 0xff,
    0x04, 0x00, 0x04, 0x00,
];

/* -------------------------------------------------------------------------
 * Linker script (ADR-0024, ADR-0112)
 *
 * Produces an ET_EXEC RV32 ELF with DT_NEEDED: libblyt32.so.  Cart code
 * calls blyt API functions via PLT; the runtime dynamic loader resolves
 * PLT/GOT entries against libblyt32.so before execution begins.
 *
 * Security requirements (ADR-0112):
 *   - No PT_INTERP: --no-dynamic-linker is added at link time
 *   - PT_GNU_RELRO + BIND_NOW: explicit relro PHDR + -z,relro -z,now
 *   - No ecall in cart code: cart calls blyt API via PLT only
 *   - Entry point in PF_X PT_LOAD segment: _blyt_entry in cart .text
 * ------------------------------------------------------------------------- */
const LINKER_SCRIPT: &str = "
ENTRY(_blyt_entry)

PHDRS {
    text    PT_LOAD      FLAGS(5);   /* r-x */
    rodata  PT_LOAD      FLAGS(4);   /* r-- */
    relro   PT_GNU_RELRO FLAGS(4);   /* RELRO: .got, .got.plt, .data.rel.ro */
    data    PT_LOAD      FLAGS(6);   /* rw- */
    dynamic PT_DYNAMIC   FLAGS(6);   /* .dynamic */
}

SECTIONS {
    . = 0x10000;

    .text : ALIGN(4) { *(.text .text.*) } :text
    .plt : ALIGN(4) { *(.plt) } :text

    . = ALIGN(4096);
    .rodata : ALIGN(4) { *(.rodata .rodata.*) } :rodata
    .eh_frame_hdr : { *(.eh_frame_hdr) } :rodata
    .eh_frame : { *(.eh_frame) } :rodata

    . = ALIGN(4096);
    .data.rel.ro : ALIGN(4) { *(.data.rel.ro .data.rel.ro.*) } :relro
    .got : ALIGN(4) { *(.got) } :relro
    .dynamic : ALIGN(4) { *(.dynamic) } :relro :dynamic
    .got.plt : ALIGN(4) { *(.got.plt) } :relro

    . = ALIGN(4096);
    .data : ALIGN(4) { *(.data .data.*) } :data
    .bss (NOLOAD) : ALIGN(4) { *(.bss .bss.*) *(COMMON) } :data
}
";

/* -------------------------------------------------------------------------
 * Error type
 * ------------------------------------------------------------------------- */

#[derive(Debug)]
pub struct BuildError(String);

impl std::fmt::Display for BuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<std::io::Error> for BuildError {
    fn from(e: std::io::Error) -> Self {
        BuildError(e.to_string())
    }
}

fn err(msg: impl Into<String>) -> BuildError {
    BuildError(msg.into())
}

/* -------------------------------------------------------------------------
 * Public entry point
 * ------------------------------------------------------------------------- */

pub fn run(project_dir: &Path, output: Option<&Path>) -> Result<(), BuildError> {
    let clang = std::env::var("BLYT_CLANG").unwrap_or_else(|_| "clang".to_string());
    let objcopy = std::env::var("BLYT_OBJCOPY").unwrap_or_else(|_| "llvm-objcopy".to_string());

    let sdk_include = find_sdk_include()?;
    let lib_dir = find_lib_dir(&sdk_include)?;

    let c_src_dir = project_dir.join("src/game/c");
    let c_files = collect_c_files(&c_src_dir)?;
    if c_files.is_empty() {
        return Err(err(format!(
            "no .c files found under {}",
            c_src_dir.display()
        )));
    }

    let build_dir = project_dir.join("build/game/c");
    fs::create_dir_all(&build_dir)?;

    let ld_script = build_dir.join("blyt_cart.ld");
    fs::write(&ld_script, LINKER_SCRIPT)?;

    let cart_info_file = build_dir.join("cart.info.bin");
    fs::write(&cart_info_file, CART_INFO)?;

    /* Generate the cart entry point stub.  _blyt_entry is the ELF e_entry:
     *   - On native RISC-V hardware: ld.so jumps here after loading
     *     libblyt32.so and libblytcommon.so; it calls blyt_main via PLT.
     *   - In the emulator: rv_create sets PC = e_entry = _blyt_entry;
     *     the PLT entry for blyt_main is resolved by dynlink before rv_run.
     * The load-time security check requires e_entry to be within an
     * executable PT_LOAD segment of the cart, which _blyt_entry satisfies. */
    let entry_stub_src = build_dir.join("_blyt_entry.c");
    fs::write(
        &entry_stub_src,
        "/* Generated by blyt build — do not edit. */\n\
         void blyt_main(void);\n\
         void _blyt_entry(void) { blyt_main(); }\n",
    )?;

    let mut obj_files = Vec::new();
    obj_files.push(compile_c(
        &clang,
        &entry_stub_src,
        &build_dir,
        &sdk_include,
    )?);
    for src in &c_files {
        let obj = compile_c(&clang, src, &build_dir, &sdk_include)?;
        obj_files.push(obj);
    }

    let raw_elf = build_dir.join("cart.elf");
    link_cart(&clang, &obj_files, &ld_script, &lib_dir, &raw_elf)?;

    let output_path = output
        .map(PathBuf::from)
        .unwrap_or_else(|| default_output(project_dir));

    finalise_cart(&objcopy, &raw_elf, &cart_info_file, &output_path)?;

    println!("built: {}", output_path.display());
    Ok(())
}

fn default_output(project_dir: &Path) -> PathBuf {
    let name = project_dir
        .file_name()
        .and_then(OsStr::to_str)
        .unwrap_or("cart");
    project_dir.with_file_name(format!("{name}.blyt"))
}

/* -------------------------------------------------------------------------
 * SDK include directory
 *
 * Looks for the directory containing blyt.h:
 *   1. $BLYT_SDK_DIR/include (or $BLYT_SDK_DIR if blyt.h is directly inside)
 *   2. Ancestors of the running binary
 * ------------------------------------------------------------------------- */

fn find_sdk_include() -> Result<PathBuf, BuildError> {
    if let Ok(sdk) = std::env::var("BLYT_SDK_DIR") {
        let sdk = PathBuf::from(sdk);
        let via_include = sdk.join("include");
        if via_include.join("blyt.h").exists() {
            return Ok(via_include);
        }
        if sdk.join("blyt.h").exists() {
            return Ok(sdk);
        }
        return Err(err(format!(
            "BLYT_SDK_DIR={} does not contain include/blyt.h",
            sdk.display()
        )));
    }

    if let Ok(exe) = std::env::current_exe() {
        for ancestor in exe.ancestors().skip(1) {
            let candidate = ancestor.join("include").join("blyt.h");
            if candidate.exists() {
                return Ok(ancestor.join("include"));
            }
        }
    }

    Err(err(
        "cannot find blyt.h — set BLYT_SDK_DIR to the blyt repository root",
    ))
}

/* -------------------------------------------------------------------------
 * Library directory
 *
 * Looks for the directory containing libblyt32.so:
 *   1. $BLYT_LIB_DIR
 *   2. <sdk_root>/build  (BLYT_SDK_DIR is the repo root; build/ has the .so)
 * ------------------------------------------------------------------------- */

fn find_lib_dir(sdk_include: &Path) -> Result<PathBuf, BuildError> {
    if let Ok(d) = std::env::var("BLYT_LIB_DIR") {
        let p = PathBuf::from(d);
        if p.join("libblyt32.so").exists() {
            return Ok(p);
        }
    }

    // sdk_include is <repo>/include; try <repo>/build
    if let Some(repo_root) = sdk_include.parent() {
        let candidate = repo_root.join("build");
        if candidate.join("libblyt32.so").exists() {
            return Ok(candidate);
        }
    }

    Err(err(
        "cannot find libblyt32.so — set BLYT_LIB_DIR to the directory \
         containing it (usually the CMake build directory)",
    ))
}

/* -------------------------------------------------------------------------
 * Source file discovery — all .c files under dir, recursively
 * ------------------------------------------------------------------------- */

fn collect_c_files(dir: &Path) -> Result<Vec<PathBuf>, BuildError> {
    if !dir.exists() {
        return Ok(Vec::new());
    }
    let mut files = Vec::new();
    collect_c_recursive(dir, &mut files)?;
    files.sort();
    Ok(files)
}

fn collect_c_recursive(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), BuildError> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_c_recursive(&path, out)?;
        } else if path.extension().and_then(OsStr::to_str) == Some("c") {
            out.push(path);
        }
    }
    Ok(())
}

/* -------------------------------------------------------------------------
 * Compilation: one .c → one .o
 * ------------------------------------------------------------------------- */

fn compile_c(
    clang: &str,
    src: &Path,
    build_dir: &Path,
    sdk_include: &Path,
) -> Result<PathBuf, BuildError> {
    let stem = src.file_stem().and_then(OsStr::to_str).unwrap_or("unknown");
    let obj = build_dir.join(format!("{stem}.o"));

    let status = Command::new(clang)
        .args([
            "--target=riscv32",
            "-march=rv32imafc",
            "-mabi=ilp32f",
            "-nostdlib",
            "-fno-exceptions",
            "-c",
        ])
        .arg("-I")
        .arg(sdk_include)
        .arg("-o")
        .arg(&obj)
        .arg(src)
        .status()
        .map_err(|e| err(format!("failed to run {clang}: {e}")))?;

    if !status.success() {
        return Err(err(format!("compilation failed: {}", src.display())));
    }
    Ok(obj)
}

/* -------------------------------------------------------------------------
 * Linking: .o files → raw ELF (ET_EXEC, dynamically linked against libblyt32.so)
 *
 * --no-dynamic-linker  suppress PT_INTERP — runtime is the loader (ADR-0119)
 * -no-pie              ET_EXEC at fixed address (Spike C validated approach)
 * -z,relro -z,now      BIND_NOW + RELRO required by ADR-0112
 * -lblyt32             creates DT_NEEDED: libblyt32.so and PLT/GOT entries
 * -rpath-link          lets lld find libblyt32.so for symbol resolution at
 *                      link time without embedding RPATH in the cart
 * ------------------------------------------------------------------------- */

fn link_cart(
    clang: &str,
    objs: &[PathBuf],
    ld_script: &Path,
    lib_dir: &Path,
    output: &Path,
) -> Result<(), BuildError> {
    let mut cmd = Command::new(clang);
    cmd.args([
        "--target=riscv32",
        "-march=rv32imafc",
        "-mabi=ilp32f",
        "-nostdlib",
        "-fuse-ld=lld",
        "-no-pie",
        "-Wl,--no-dynamic-linker",
        "-Wl,-z,relro",
        "-Wl,-z,now",
        "-Wl,--build-id=none",
    ])
    .arg(format!("-T{}", ld_script.display()))
    .arg("-o")
    .arg(output);

    for obj in objs {
        cmd.arg(obj);
    }

    cmd.arg("-L").arg(lib_dir).arg("-lblyt32");
    cmd.arg(format!("-Wl,-rpath-link,{}", lib_dir.display()));

    let status = cmd
        .status()
        .map_err(|e| err(format!("failed to run {clang}: {e}")))?;

    if !status.success() {
        return Err(err("link failed"));
    }
    Ok(())
}

/* -------------------------------------------------------------------------
 * Cart finalisation: inject .cart.info, strip toolchain metadata
 *
 * .riscv.attributes and .comment are toolchain metadata with no runtime use.
 * ------------------------------------------------------------------------- */

fn finalise_cart(
    objcopy: &str,
    raw_elf: &Path,
    cart_info_file: &Path,
    output: &Path,
) -> Result<(), BuildError> {
    let status = Command::new(objcopy)
        .arg("--add-section")
        .arg(format!(".cart.info={}", cart_info_file.display()))
        .arg("--set-section-flags")
        .arg(".cart.info=alloc,readonly")
        .arg("--remove-section=.riscv.attributes")
        .arg("--remove-section=.comment")
        .arg(raw_elf)
        .arg(output)
        .status()
        .map_err(|e| err(format!("failed to run {objcopy}: {e}")))?;

    if !status.success() {
        return Err(err("objcopy (finalise) failed"));
    }
    Ok(())
}
