records:
  Globals:
    fields:
      - { name: frame, type: i32 }
  Player:
    fields:
      - { name: x, type: i32 }
      - { name: y, type: i32 }
state_buffers:
  globals:
    record: Globals
    count: 1
  player:
    record: Player
    count: 1
