//! Blyt cart SDK — Rust bindings for the blyt runtime API.
//!
//! `#![no_std]`.  The `blyt` crate provides:
//!
//! - Safe wrappers around the C API declared in `blyt.h`
//! - A `#[global_allocator]` backed by `libblytc`'s `malloc`/`free`
//! - A `#[panic_handler]` that calls `abort()` from `libblytc`
//!
//! Cart code must not define its own panic handler or global allocator.

#![no_std]

use core::ffi::c_char;

// -------------------------------------------------------------------------
// Raw C API
// -------------------------------------------------------------------------

extern "C" {
    fn blyt_console_debug(s: *const c_char);
    fn blyt_quit();
    fn blyt_frame_done();
    // libblytc allocator
    fn malloc(size: usize) -> *mut core::ffi::c_void;
    fn free(ptr: *mut core::ffi::c_void);
    fn realloc(ptr: *mut core::ffi::c_void, size: usize) -> *mut core::ffi::c_void;
    fn abort() -> !;
}

// -------------------------------------------------------------------------
// Public cart API
// -------------------------------------------------------------------------

/// Write a debug message to the host console.
///
/// `s` is truncated to 255 bytes if longer; null bytes in the middle of `s`
/// terminate the output early (C string semantics in the host).
pub fn console_debug(s: &str) {
    let mut buf = [0u8; 256];
    let len = s.len().min(255);
    buf[..len].copy_from_slice(&s.as_bytes()[..len]);
    // buf[len] is 0 from zero-initialisation — null terminator.
    unsafe { blyt_console_debug(buf.as_ptr().cast()) }
}

/// Signal the runtime that the cart is ready to exit.
///
/// Call from `blyt_cart_update` when the cart decides it has finished.
/// The runtime will stop calling `blyt_cart_update` and `blyt_cart_draw`
/// after the current frame and proceed with teardown.
pub fn quit() {
    unsafe { blyt_quit() }
}

/// Signal the end of one update+draw frame.
///
/// Normally called automatically by `libblytcommon` after each
/// `blyt_cart_draw()`; cart code does not need to call this directly.
pub fn frame_done() {
    unsafe { blyt_frame_done() }
}

// -------------------------------------------------------------------------
// Global allocator — backed by libblytc malloc/free
// -------------------------------------------------------------------------

use core::alloc::{GlobalAlloc, Layout};

struct BlytAlloc;

unsafe impl GlobalAlloc for BlytAlloc {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        // libblytc malloc guarantees pointer-size alignment.  Over-aligned
        // layouts are not yet handled; alloc returns null and the caller
        // will hit the OOM path.  Sufficient for Phase 7 heap usage.
        unsafe { malloc(layout.size()) as *mut u8 }
    }

    unsafe fn dealloc(&self, ptr: *mut u8, _layout: Layout) {
        unsafe { free(ptr as *mut core::ffi::c_void) }
    }

    unsafe fn realloc(&self, ptr: *mut u8, _layout: Layout, new_size: usize) -> *mut u8 {
        unsafe { realloc(ptr as *mut core::ffi::c_void, new_size) as *mut u8 }
    }
}

#[global_allocator]
static ALLOC: BlytAlloc = BlytAlloc;

// -------------------------------------------------------------------------
// Panic handler — abort via libblytc
// -------------------------------------------------------------------------

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    unsafe { abort() }
}

// -------------------------------------------------------------------------
// Lua export support (feature "lua") — enabled for Lua+Rust hybrid carts.
//
// Re-exports the lua_export attribute macro from blyt-lua-macros.
// cart_lua_modules is generated by the devtool as a C object file for all
// Lua carts (C, Rust, and mixed); Rust carts no longer define it here.
// -------------------------------------------------------------------------

#[cfg(feature = "lua")]
pub mod lua {
    pub use blyt_lua_macros::lua_export;

    // Matches blyt_lua_export_entry_t in runtime/guest/include/blyt.h.
    #[repr(C)]
    pub struct BlytLuaExportEntry {
        pub lua_name:  [u8; 32],
        pub fn_sym:    [u8; 64],
        pub wrap_sym:  [u8; 64],
        pub nargs:     u8,
        pub arg_types: [u8; 4],
        pub ret_type:  u8,
        pub flags:     u8,
        pub pad:       u8,
    }

    pub const LUA_TYPE_VOID: u8 = 0;
    pub const LUA_TYPE_I32:  u8 = 1;
    pub const LUA_TYPE_U32:  u8 = 2;
    pub const LUA_TYPE_F32:  u8 = 3;
    pub const LUA_TYPE_BOOL: u8 = 4;

    // BLYT_LUA_EXPORT_FLAG_BRIDGED (ADR-0130): the WASM host invokes the
    // wrapper through the ECALL-bridged Lua C API instead of typed register
    // conversion — enables strings, tables, >4 args, and multiple returns.
    pub const LUA_EXPORT_FLAG_BRIDGED: u8 = 0x01;

    /// Opaque Lua state token passed to raw `#[lua_export(..., raw)]` bodies.
    /// On rv32 it is a real `lua_State *`; on WASM it is an opaque per-call
    /// token understood by the ECALL bridge (libblyt32lua-bridge.so).
    pub type LuaState = *mut ::core::ffi::c_void;

    /// Restricted Lua C API for raw `#[lua_export(..., raw)]` wrapper bodies.
    /// Mirrors runtime/guest/include/blyt_lua_internal.h (the blyt32lua.sym
    /// surface): Lua 5.4 with LUA_32BITS=1, so lua_Integer = i32 and
    /// lua_Number = f32.  Deliberately omits code-loading and call entry
    /// points — cart code communicates with Lua exclusively through the
    /// export boundary.
    pub mod capi {
        use super::LuaState;
        use core::ffi::{c_char, c_int};

        pub const LUA_TNONE: c_int = -1;
        pub const LUA_TNIL: c_int = 0;
        pub const LUA_TBOOLEAN: c_int = 1;
        pub const LUA_TLIGHTUSERDATA: c_int = 2;
        pub const LUA_TNUMBER: c_int = 3;
        pub const LUA_TSTRING: c_int = 4;
        pub const LUA_TTABLE: c_int = 5;
        pub const LUA_TFUNCTION: c_int = 6;
        pub const LUA_TUSERDATA: c_int = 7;
        pub const LUA_TTHREAD: c_int = 8;

        extern "C" {
            // Stack inspection / manipulation.
            pub fn lua_gettop(l: LuaState) -> c_int;
            pub fn lua_settop(l: LuaState, idx: c_int);
            pub fn lua_type(l: LuaState, idx: c_int) -> c_int;
            pub fn lua_typename(l: LuaState, tp: c_int) -> *const c_char;

            // Argument extraction.
            pub fn lua_tointegerx(l: LuaState, idx: c_int, isnum: *mut c_int) -> i32;
            pub fn lua_tonumberx(l: LuaState, idx: c_int, isnum: *mut c_int) -> f32;
            pub fn lua_toboolean(l: LuaState, idx: c_int) -> c_int;
            pub fn lua_tolstring(l: LuaState, idx: c_int, len: *mut usize) -> *const c_char;
            pub fn luaL_checkinteger(l: LuaState, arg: c_int) -> i32;
            pub fn luaL_checknumber(l: LuaState, arg: c_int) -> f32;
            pub fn luaL_checklstring(l: LuaState, arg: c_int, len: *mut usize) -> *const c_char;

            // Result push.
            pub fn lua_pushinteger(l: LuaState, n: i32);
            pub fn lua_pushnumber(l: LuaState, n: f32);
            pub fn lua_pushboolean(l: LuaState, b: c_int);
            pub fn lua_pushnil(l: LuaState);
            pub fn lua_pushstring(l: LuaState, s: *const c_char) -> *const c_char;
            pub fn lua_pushlstring(l: LuaState, s: *const c_char, len: usize) -> *const c_char;

            // Tables.
            pub fn lua_createtable(l: LuaState, narr: c_int, nrec: c_int);
            pub fn lua_geti(l: LuaState, idx: c_int, i: i32) -> c_int;
            pub fn lua_seti(l: LuaState, idx: c_int, i: i32);
            pub fn lua_rawlen(l: LuaState, idx: c_int) -> u32;
            pub fn lua_next(l: LuaState, idx: c_int) -> c_int;

            // Errors.  lua_error never returns; luaL_error is variadic.
            pub fn lua_error(l: LuaState) -> c_int;
            pub fn luaL_error(l: LuaState, fmt: *const c_char, ...) -> c_int;
        }
    }

    // Used by proc-macro generated statics to build BlytLuaExportEntry at
    // compile time without requiring heap allocation.
    pub const fn str_to_fixed<const N: usize>(s: &str) -> [u8; N] {
        let src = s.as_bytes();
        let mut arr = [0u8; N];
        let mut i = 0;
        while i < src.len() && i + 1 < N {
            arr[i] = src[i];
            i += 1;
        }
        arr
    }

    // Matches blyt_lua_regtab_entry_t in runtime/guest/include/blyt.h.
    // Placed in .lua_regtab by #[lua_export] generated statics; iterated by
    // the devtool-generated C cart_lua_modules at cart startup.
    #[repr(C)]
    pub struct BlytLuaRegtabEntry {
        // NULL = global export; non-NULL = module name (null-terminated).
        pub module_name: *const u8,
        pub lua_fn_name: *const u8,
        pub wrapper: unsafe extern "C" fn(*mut ::core::ffi::c_void) -> ::core::ffi::c_int,
    }

    // SAFETY: BlytLuaRegtabEntry is only placed in a static section and read
    // by cart_lua_modules; no mutation or cross-thread access occurs.
    unsafe impl Sync for BlytLuaRegtabEntry {}
}

#[cfg(feature = "lua")]
pub use lua::{lua_export, BlytLuaRegtabEntry};
