#!/usr/bin/env python3
"""Embed binary files as C byte arrays.

Usage: bin2c.py name1 file1 [name2 file2 ...] output.c

For each (name, file) pair, emits:
    const unsigned char <name>[] = { 0xNN, ... };
    const unsigned int  <name>_len = <size>;
"""
import sys


def main():
    args = sys.argv[1:]
    if len(args) < 3 or len(args) % 2 == 0:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    output = args[-1]
    pairs = args[:-1]

    with open(output, "w") as out:
        out.write("/* Generated by cmake/bin2c.py — do not edit. */\n")
        out.write("#include <stddef.h>\n\n")
        for i in range(0, len(pairs), 2):
            name = pairs[i]
            path = pairs[i + 1]
            with open(path, "rb") as f:
                data = f.read()
            hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
            out.write(f"const unsigned char {name}[] = {{{hex_bytes}}};\n")
            out.write(f"const unsigned int {name}_len = {len(data)};\n\n")


if __name__ == "__main__":
    main()
