# blyt_gen_rv32_sizeof.cmake — turn the rv32-compiled size probe into a header.
#
# Run in script mode (cmake -P) as a build step. Invokes `${NM} --print-size`
# on the probe object built by the rv32 toolchain (runtime/shared/
# blyt_lua_rv32_sizeof_probe.c) and emits ${OUT} — a header of
# `#define BLYT_RV32_SIZEOF_<type> <n>u` constants the host-Lua heap-accounting
# seam (BLYT_HOSTLUA_HEAP_SEAM, #231) substitutes for host `sizeof` so
# guest_heap_used is counted at the 32-bit canonical size on every leg.
#
# Inputs (-D on the cmake -P command line): NM (llvm-nm), OBJ (probe .o), OUT
# (header to write). Each probe symbol `blyt_rv32_sz__T` is a char[sizeof(T)],
# so the ELF symbol size read back here IS sizeof(T) as the rv32 ABI lays it out.

if(NOT NM OR NOT OBJ OR NOT OUT)
  message(FATAL_ERROR "blyt_gen_rv32_sizeof: NM, OBJ and OUT must all be set")
endif()

execute_process(
  COMMAND "${NM}" --print-size --defined-only "${OBJ}"
  OUTPUT_VARIABLE _nm_out
  RESULT_VARIABLE _nm_rc
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT _nm_rc EQUAL 0)
  message(FATAL_ERROR "blyt_gen_rv32_sizeof: '${NM} --print-size ${OBJ}' failed (${_nm_rc})")
endif()

set(_body "")
set(_count 0)
string(REPLACE "\n" ";" _lines "${_nm_out}")
foreach(_ln IN LISTS _lines)
  # nm --print-size line: <addr> <size> <symtype> blyt_rv32_sz__<name>
  if(_ln MATCHES "^[0-9a-fA-F]+ +([0-9a-fA-F]+) +[A-Za-z] +blyt_rv32_sz__([A-Za-z0-9_]+)$")
    set(_hex "${CMAKE_MATCH_1}")
    set(_name "${CMAKE_MATCH_2}")
    math(EXPR _dec "0x${_hex}")
    string(APPEND _body "#define BLYT_RV32_SIZEOF_${_name} ${_dec}u\n")
    math(EXPR _count "${_count} + 1")
  endif()
endforeach()

if(_count EQUAL 0)
  message(FATAL_ERROR "blyt_gen_rv32_sizeof: no blyt_rv32_sz__ symbols found in ${OBJ}")
endif()

file(
  WRITE "${OUT}"
  "/* GENERATED by cmake/blyt_gen_rv32_sizeof.cmake from\n"
  " * runtime/shared/blyt_lua_rv32_sizeof_probe.c compiled by the rv32 (ilp32d)\n"
  " * guest toolchain — DO NOT EDIT. Each constant is the canonical 32-bit size\n"
  " * of a Lua internal type; the host-Lua heap seam (BLYT_HOSTLUA_HEAP_SEAM,\n"
  " * #231) substitutes these for host sizeof so guest_heap_used is counted at\n"
  " * rv32 sizes on the 64-bit desktop, matching wasm + rv32 hardware. */\n"
  "#ifndef BLYT_LUA_RV32_SIZEOF_H\n"
  "#define BLYT_LUA_RV32_SIZEOF_H\n\n"
  "${_body}\n"
  "#endif /* BLYT_LUA_RV32_SIZEOF_H */\n")

message(STATUS "blyt_gen_rv32_sizeof: wrote ${_count} rv32 sizes to ${OUT}")
