# cmake/riscv64-linux-gnu.cmake — cross-compilation toolchain for riscv64 Linux.
#
# Used to cross-compile blyt_native (the LP64 launcher) on an x86-64 CI host:
#
#   cmake -B build-riscv64 -G Ninja \
#       -DCMAKE_TOOLCHAIN_FILE=cmake/riscv64-linux-gnu.cmake \
#       -DBLYT_PREGENERATED_DIR=$PWD/build/generated/flatbuffers
#   cmake --build build-riscv64 --target blyt_native
#
# BLYT_PREGENERATED_DIR points to FlatBuffers headers already generated by the
# host build.  The code-generation step (which would try to execute a riscv64
# flatcc_cli binary on an x86-64 host) is skipped.
#
# Requires: gcc-riscv64-linux-gnu on the host.

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(CMAKE_C_COMPILER riscv64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER riscv64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH /usr/riscv64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
